# Generated by Django 3.1.3 on 2020-12-03 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='recentdetail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='recentimage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='recentname',
        ),
        migrations.RemoveField(
            model_name='product',
            name='recentoffer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='recentprice',
        ),
    ]
